### ISSUE TITLE
dependency does not exist

### ISSUE THREAD

**Issue by Deub27** [JLogical-Apps/flood#5]
Hi, the dependency git@github.com:SKnoedler/snapshot.git seems unknown.

When i run 'melos bs' on the flood_template

Seems to be an issue with the dependency declared here: https://github.com/jaboyc/xcodeproj/blob/master/pubspec.yaml

**Comment by jaboyc** [comment]
Thank you for catching that @Deub27 . I have fixed the dependency in this commit: https://github.com/jaboyc/xcodeproj/commit/a06c08297ca8611478b76313760ff70e7f1df70f 

`melos bs` now runs fine for me. Let me know if you still continue to have dependency issues. Closing for now.
